import type { IssueGroup } from '@mahoraga/core';
import type { AdaptationResult } from './adaptation-loop.js';

/**
 * Options for creating a PR.
 */
export interface PRCreateOptions {
  /** Base branch to merge into */
  baseBranch: string;
  /** Whether to create as draft */
  draft: boolean;
  /** Working directory */
  workDir: string;
}

/**
 * Result of PR creation.
 */
export interface PRCreateResult {
  /** PR URL if created successfully */
  prUrl?: string;
  /** Error message if failed */
  error?: string;
}

/**
 * Create a PR with rich context from the Mahoraga analysis.
 * @param branchName - Name of the fix branch
 * @param issues - Issues addressed by this PR
 * @param adaptationResult - Result from the adaptation loop
 * @param options - PR creation options
 * @returns PR creation result
 */
export async function createPR(
  branchName: string,
  issues: IssueGroup[],
  adaptationResult: AdaptationResult,
  options: PRCreateOptions,
): Promise<PRCreateResult> {
  const title = buildPRTitle(issues);
  const body = buildPRBody(issues, adaptationResult);

  const { execFile } = await import('node:child_process');
  const { promisify } = await import('node:util');
  const exec = promisify(execFile);

  try {
    const args = [
      'pr',
      'create',
      '--title',
      title,
      '--body',
      body,
      '--base',
      options.baseBranch,
      '--head',
      branchName,
    ];

    if (options.draft) {
      args.push('--draft');
    }

    const { stdout } = await exec('gh', args, {
      cwd: options.workDir,
      timeout: 30_000,
    });

    return { prUrl: stdout.trim() };
  } catch (error) {
    return {
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * Build a PR title from the issues being fixed.
 * @param issues - Issues addressed by this PR
 * @returns PR title string
 */
export function buildPRTitle(issues: IssueGroup[]): string {
  if (issues.length === 1) {
    return `fix: ${issues[0]!.title}`;
  }
  return `fix: address ${issues.length} UI issues detected by Mahoraga`;
}

/**
 * Build a rich PR body with analytics context.
 * @param issues - Issues addressed
 * @param result - Adaptation loop result
 * @returns Markdown PR body
 */
export function buildPRBody(
  issues: IssueGroup[],
  result: AdaptationResult,
): string {
  const sections: string[] = [];

  sections.push('## Mahoraga Auto-Fix\n');
  sections.push(
    'This PR was automatically generated by [Mahoraga](https://github.com/mahoraga) based on user behavior analytics.\n',
  );

  // Analytics summary
  sections.push('### Analytics Summary\n');
  for (const issue of issues) {
    sections.push(`#### ${issue.title}`);
    sections.push(`- **Severity:** ${issue.severity}`);
    sections.push(`- **Frequency:** ${issue.frequency} sessions affected`);
    sections.push(`- **Detection Rule:** ${issue.ruleId}`);
    sections.push(`- **Description:** ${issue.description}`);

    // Affected elements
    if (issue.affectedElements.length > 0) {
      sections.push('\n**Affected Elements:**');
      for (const el of issue.affectedElements) {
        let line = `- \`${el.selector}\` on ${el.url}`;
        if (el.componentName) {
          line += ` (${el.componentName})`;
        }
        sections.push(line);
      }
    }

    // Evidence
    if (issue.evidence.length > 0) {
      sections.push('\n**Evidence:**');
      for (const ev of issue.evidence) {
        sections.push(`- ${ev.description}`);
      }
    }

    sections.push('');
  }

  // Adaptation loop info
  sections.push('### Fix Verification\n');
  sections.push(
    `- **Adaptation attempts:** ${result.attempts}`,
  );
  sections.push(
    `- **Verification test:** ${result.success ? 'PASSED' : 'FAILED'}`,
  );

  if (result.executionResult.costUsd !== undefined) {
    sections.push(
      `- **Cost:** $${result.executionResult.costUsd.toFixed(2)}`,
    );
  }

  if (result.attemptErrors.length > 0) {
    sections.push('\n<details><summary>Attempt History</summary>\n');
    for (const err of result.attemptErrors) {
      sections.push(`- ${err}`);
    }
    sections.push('\n</details>');
  }

  sections.push(
    '\n---\n*Generated by Mahoraga — Self-Evolving Frontend Intelligence*',
  );

  return sections.join('\n');
}
