import type { IssueGroup } from '@mahoraga/core';

/**
 * Result of generating a localized test.
 */
export interface GeneratedTest {
  /** File path where the test was written */
  testPath: string;
  /** Test file content */
  content: string;
  /** Command to run the test */
  runCommand: string;
}

/**
 * Generate a localized test that mimics the user journey which triggered the issue.
 * The test verifies the fix addresses the root cause.
 * @param issue - The detected issue
 * @param workDir - Working directory of the project
 * @returns Generated test details
 */
export function generateTest(
  issue: IssueGroup,
  workDir: string,
): GeneratedTest {
  const testFileName = `mahoraga-verify-${issue.ruleId}-${sanitizeForFilename(issue.id)}.test.ts`;
  const testPath = `${workDir}/__mahoraga_tests__/${testFileName}`;

  let content: string;

  switch (issue.ruleId) {
    case 'rage-clicks':
      content = generateRageClickTest(issue);
      break;
    case 'error-spikes':
      content = generateErrorSpikeTest(issue);
      break;
    default:
      content = generateGenericTest(issue);
      break;
  }

  return {
    testPath,
    content,
    runCommand: `npx vitest run ${testPath}`,
  };
}

function generateRageClickTest(issue: IssueGroup): string {
  const selectors = issue.affectedElements.map((e) => e.selector);

  return `import { describe, it, expect } from 'vitest';

/**
 * Auto-generated by Mahoraga to verify rage-click fix.
 * Issue: ${issue.title}
 * Affected selectors: ${selectors.join(', ')}
 */
describe('Mahoraga: ${escapeString(issue.title)}', () => {
  it('should render the affected element as interactive', () => {
    // Verify the element exists and is interactable
    // This test validates the fix addresses the rage-click root cause
    ${selectors.map((s) => `
    // Selector: ${s}
    // The element should either:
    // 1. Have proper click handlers
    // 2. Be a native interactive element (button, a, input)
    // 3. Have appropriate ARIA roles
    expect(true).toBe(true); // Placeholder — agent should enhance this test
    `).join('\n')}
  });

  it('should have accessible click targets', () => {
    // Verify click targets meet minimum size requirements (44x44px)
    ${selectors.map((s) => `
    // Selector: ${s} should have adequate click target size
    expect(true).toBe(true); // Placeholder — agent should enhance this test
    `).join('\n')}
  });
});
`;
}

function generateErrorSpikeTest(issue: IssueGroup): string {
  const errorMessages = issue.evidence
    .flatMap((e) => e.eventSummaries)
    .map((s) => s.summary)
    .slice(0, 3);

  return `import { describe, it, expect } from 'vitest';

/**
 * Auto-generated by Mahoraga to verify error-spike fix.
 * Issue: ${issue.title}
 */
describe('Mahoraga: ${escapeString(issue.title)}', () => {
  it('should not throw the previously spiking error', () => {
    // Verify the error that was spiking no longer occurs
    // Error messages observed:
    ${errorMessages.map((m) => `// - ${m}`).join('\n    ')}
    expect(true).toBe(true); // Placeholder — agent should enhance this test
  });

  it('should handle edge cases gracefully', () => {
    // Verify error handling covers the cases that caused the spike
    expect(true).toBe(true); // Placeholder — agent should enhance this test
  });
});
`;
}

function generateGenericTest(issue: IssueGroup): string {
  return `import { describe, it, expect } from 'vitest';

/**
 * Auto-generated by Mahoraga to verify fix.
 * Issue: ${issue.title}
 * Rule: ${issue.ruleId}
 */
describe('Mahoraga: ${escapeString(issue.title)}', () => {
  it('should fix the detected issue', () => {
    // This test should be enhanced by the agent to verify the specific fix
    expect(true).toBe(true); // Placeholder — agent should enhance this test
  });
});
`;
}

function sanitizeForFilename(str: string): string {
  return str.replace(/[^a-zA-Z0-9-]/g, '-').substring(0, 50);
}

function escapeString(str: string): string {
  return str.replace(/'/g, "\\'").replace(/\n/g, ' ');
}
