import type { IssueGroup } from '@mahoraga/core';

/**
 * Result of generating a localized test.
 */
export interface GeneratedTest {
  /** File path where the test was written */
  testPath: string;
  /** Test file content */
  content: string;
  /** Command to run the test */
  runCommand: string;
}

/**
 * Generate a localized test that mimics the user journey which triggered the issue.
 * The test verifies the fix addresses the root cause.
 * @param issue - The detected issue
 * @param workDir - Working directory of the project
 * @returns Generated test details
 */
export function generateTest(
  issue: IssueGroup,
  workDir: string,
): GeneratedTest {
  const testFileName = `mahoraga-verify-${issue.ruleId}-${sanitizeForFilename(issue.id)}.test.ts`;
  const testPath = `${workDir}/__mahoraga_tests__/${testFileName}`;

  let content: string;

  switch (issue.ruleId) {
    case 'rage-clicks':
      content = generateRageClickTest(issue);
      break;
    case 'error-spikes':
      content = generateErrorSpikeTest(issue);
      break;
    default:
      content = generateGenericTest(issue);
      break;
  }

  return {
    testPath,
    content,
    runCommand: `npx vitest run ${testPath}`,
  };
}

function generateRageClickTest(issue: IssueGroup): string {
  const selectors = issue.affectedElements.map((e) => e.selector);
  const urls = [...new Set(issue.affectedElements.map((e) => e.url))];

  return `import { describe, it } from 'vitest';

/**
 * Auto-generated by Mahoraga to verify rage-click fix.
 * Issue: ${issue.title}
 * Affected selectors: ${selectors.join(', ')}
 * Affected URLs: ${urls.join(', ')}
 *
 * MAHORAGA: Replace every \`throw new Error\` placeholder below with real
 * assertions that verify the fix. Import the component under test, render it,
 * and assert the click handler / interactive state is correct.
 * The adaptation loop will keep retrying until this test passes.
 */
describe('Mahoraga: ${escapeString(issue.title)}', () => {
  it('should render the affected element as interactive', () => {
    // Verify the element exists and is interactable after the fix.
    // The element should either:
    //   1. Have a proper click handler (onClick / addEventListener)
    //   2. Be a native interactive element (button, a, input)
    //   3. Have an appropriate ARIA role (role="button", etc.)
    //
    // Affected selectors: ${selectors.join(', ')}
    throw new Error(
      'Placeholder — replace with assertions that verify the fixed element is interactive',
    );
  });

  it('should have accessible click targets', () => {
    // Verify click targets meet minimum recommended size (44×44 CSS px).
    // ${selectors.map((s) => `Selector: ${s}`).join(', ')}
    throw new Error(
      'Placeholder — replace with assertions that verify click target size / accessibility',
    );
  });
});
`;
}

function generateErrorSpikeTest(issue: IssueGroup): string {
  const errorMessages = issue.evidence
    .flatMap((e) => e.eventSummaries)
    .map((s) => s.summary)
    .slice(0, 3);

  return `import { describe, it } from 'vitest';

/**
 * Auto-generated by Mahoraga to verify error-spike fix.
 * Issue: ${issue.title}
 *
 * MAHORAGA: Replace every \`throw new Error\` placeholder below with real
 * assertions. Import the module / component that was throwing, exercise the
 * code path that caused the spike, and assert the error no longer occurs.
 * The adaptation loop will keep retrying until this test passes.
 *
 * Error messages observed:
 * ${errorMessages.map((m) => `- ${m}`).join('\n * ')}
 */
describe('Mahoraga: ${escapeString(issue.title)}', () => {
  it('should not throw the previously spiking error', () => {
    // Exercise the code path that was spiking and assert it no longer throws.
    throw new Error(
      'Placeholder — replace with assertions that verify the error no longer occurs',
    );
  });

  it('should handle edge cases gracefully', () => {
    // Cover the boundary conditions that triggered the spike.
    throw new Error(
      'Placeholder — replace with assertions that verify edge-case error handling',
    );
  });
});
`;
}

function generateGenericTest(issue: IssueGroup): string {
  return `import { describe, it } from 'vitest';

/**
 * Auto-generated by Mahoraga to verify fix.
 * Issue: ${issue.title}
 * Rule: ${issue.ruleId}
 *
 * MAHORAGA: Replace the \`throw new Error\` placeholder below with real
 * assertions that verify the fix addresses the root cause.
 * The adaptation loop will keep retrying until this test passes.
 */
describe('Mahoraga: ${escapeString(issue.title)}', () => {
  it('should fix the detected issue', () => {
    // Import the affected module / component and assert the fix is in effect.
    throw new Error(
      'Placeholder — replace with assertions that verify the fix for: ${escapeString(issue.title)}',
    );
  });
});
`;
}

function sanitizeForFilename(str: string): string {
  return str.replace(/[^a-zA-Z0-9-]/g, '-').substring(0, 50);
}

function escapeString(str: string): string {
  return str.replace(/'/g, "\\'").replace(/\n/g, ' ');
}
